from selenium import webdriver
from selenium.webdriver.support.select import Select
from time import sleep
from selenium.webdriver.common.keys import Keys
import random
try:
    deriver = webdriver.Chrome()
    deriver.get('http://localhost/ranzhi/www/sys/user-login.html')
    deriver.maximize_window()
    # deriver.implicitly_wait(10) 
    deriver.find_element_by_id('account').send_keys('admin')
    deriver.find_element_by_id('password').send_keys('123456')
    deriver.find_element_by_id('submit').click()
    sleep(1)
    deriver.find_element_by_xpath('//*[@id="s-menu-4"]/button/img').click()
    sleep(2)
    frame = deriver.find_element_by_xpath('//*[@id="iframe-4"]')
    deriver.switch_to.frame(frame)
    deriver.find_element_by_partial_link_text('创建文档库').click()
    sleep(1)
    deriver.find_element_by_xpath('//*[@id="libType"]/option[1]').click()
    deriver.find_element_by_id('name').send_keys('Python13')
    deriver.find_element_by_xpath('//*[@id="users_chosen"]/ul').click()
    deriver.find_element_by_xpath('//*[@id="users_chosen"]/div/ul').click()
    deriver.find_element_by_id('groups1').click()
    deriver.find_element_by_id('submit').click()
    sleep(2)
    deriver.find_element_by_xpath('//*[@id="treebox"]/div[2]/div/a').click()
    sleep(1)
    deriver.find_element_by_xpath('//*[@name="children[1]"]').send_keys('研发部')
    deriver.find_element_by_xpath('//*[@name="children[2]"]').send_keys('财务部')
    deriver.find_element_by_xpath('//*[@name="children[3]"]').send_keys('测试部')
    deriver.find_element_by_id('submit').click()
    sleep(1)
    deriver.back()
    sleep(1)
    frame = deriver.find_element_by_xpath('//*[@id="iframe-4"]')
    deriver.switch_to.frame(frame)
    deriver.find_element_by_xpath('//*[@id="menuActions"]/a').click()
    select1 = deriver.find_element_by_xpath('//*[@id="module"]')
    desp = Select(select1)
    desp.select_by_index(1)
    deriver.find_element_by_xpath('//*[@id="users_chosen"]/ul').click()
    deriver.find_element_by_xpath('//*[@id="users_chosen"]/div/ul').click()
    deriver.find_element_by_id('groups1').click()
    texttype = ('typetext' if random.randint(0,1)==1 else 'typeurl')
    deriver.find_element_by_id(texttype).click()
    deriver.find_element_by_xpath('//*[@id="title"]').send_keys('啄木鸟学院')
    sleep(1)
    if texttype == 'typetext':
        frame1 = deriver.find_element_by_id('ueditor_0')
        deriver.switch_to.frame(frame1)
        sleep(1)
        deriver.find_element_by_xpath('/html/body').send_keys('你好')
        sleep(1)
        deriver._switch_to.parent_frame()
        # deriver.switch_to.default_content()
        # frame = deriver.find_element_by_xpath('//*[@id="iframe-4"]')
        # deriver.switch_to.frame(frame)
        sleep(1)
    else:
        deriver.find_element_by_xpath('//*[@id="url"]').send_keys('https://www.baidu.com')
    deriver.find_element_by_xpath('//*[@id="keywords"]').send_keys('关键字')
    deriver.find_element_by_xpath('//*[@id="digest"]').send_keys('摘要')
    sleep(1)
    deriver.find_element_by_xpath('//*[@id="fileBox1"]/tbody/tr/td[1]/div/input').send_keys("C:\workspace\python\day07\exit.png")
    deriver.find_element_by_id('submit').click()
    # deriver.find_element_by_xpath('//*[@id="docList"]/tbody/tr/td[6]/a[2]').click()
    # deriver.switch_to.alert.accept()
#-------------------------------------------------------------------------------------------------------
    #添加公司
    # deriver.find_element_by_xpath('//*[@id="shortcutBox"]/div/div[1]/div/a/h3').click()
    # deriver.find_element_by_id('account').send_keys('Tomcat')
    # deriver.find_element_by_id('realname').send_keys('aaa')
    # deriver.find_element_by_id('genderm').click()
    # #选中select元素
    # select1 = deriver.find_element_by_id('dept')
    # #使用select进行处理
    # dept = Select(select1)
    # #根据value来选中
    # # dept.select_by_index(3)
    # dept.select_by_value('11')
    # select2 = deriver.find_element_by_id('role')
    # dept = Select(select2)
    # dept.select_by_value('pm')
    # deriver.find_element_by_id('password1').send_keys('123456')
    # deriver.find_element_by_id('password2').send_keys('123456')
    # deriver.find_element_by_id('email').send_keys('1594203964@qq.com')
    # deriver.find_element_by_id('submit').click()
    # sleep(2)
#---------------------------------------------------------------------------------------------------------------------
    # deriver.find_element_by_xpath('/html/body/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[11]/a[3]').click()
    # sleep(1)
    # #取消
    # deriver.switch_to.alert.dismiss()
    # #确定
    # deriver.find_element_by_xpath('/html/body/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[11]/a[3]').click()
    # sleep(1)
    # deriver.switch_to.alert.accept()


except Exception as e:
    print(e)
finally:
    sleep(2)
    # deriver.close()
